
from enum import Enum

class Feature(Enum):
    MEAN_ABSOLUTE_DIFFERENCING_TRANSACTION_TIMESTAMPS = 1
    MEAN_ABSOLUTE_DIFFERENCING_TRANSACTION_AMOUNT = 2
    MEDIAN_LOCATION = 3
    MEDIAN_TARGET_IP = 4
    MEDIAN_DEST_IP = 5
